// Supabase sync helper — writes data to Supabase in parallel with Prisma
// Uses respondent `code` as the key (not Prisma CUID id)
// Supabase tables use uuid PKs generated by Supabase itself
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const supabaseKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY

if (!supabaseUrl || !supabaseKey) {
  console.error('[Supabase] Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY')
}

export const supabase = (supabaseUrl && supabaseKey)
  ? createClient(supabaseUrl, supabaseKey, {
      auth: { persistSession: false }
    })
  : null

// ─── Helper: get respondent UUID from Supabase by code ───────────────
async function getSupabaseRespondentId(code: string): Promise<string | null> {
  if (!supabase) return null
  const { data, error } = await supabase
    .from('respondents')
    .select('id')
    .eq('code', code)
    .maybeSingle()
  if (error) {
    console.error('[Supabase] Error fetching respondent ID:', error.message)
    return null
  }
  return data?.id ?? null
}

// ─── Respondent sync (upsert by code, let Supabase generate UUID) ────
export async function syncRespondent(data: {
  code: string
  school: string | null
  status: string
  current_stage: string
  stage_index: number
  high_risk: boolean
  consent_given: boolean
  started_at: string
  completed_at: string | null
}) {
  if (!supabase) { console.warn('[Supabase] Client null — skipping sync'); return }
  console.log('[Supabase] Syncing respondent:', data.code)
  const { error } = await supabase
    .from('respondents')
    .upsert({
      code: data.code,
      school: data.school,
      status: data.status,
      current_stage: data.current_stage,
      stage_index: data.stage_index,
      high_risk: data.high_risk,
      consent_given: data.consent_given,
      started_at: data.started_at,
      completed_at: data.completed_at,
    }, { onConflict: 'code' })
  if (error) console.error('[Supabase] Error syncing respondent:', error.message, error.details)
  else console.log('[Supabase] Respondent synced OK:', data.code)
}

// ─── Demographics sync ───────────────────────────────────────────────
export async function syncDemographics(respondentCode: string, data: Record<string, unknown>) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync demographics — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing demographics for:', respondentCode, 'uuid:', respondentId)
  const { error } = await supabase
    .from('demographics')
    .upsert({
      respondent_id: respondentId,
      data: data,  // jsonb
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing demographics:', error.message, error.details)
  else console.log('[Supabase] Demographics synced OK')
}

// ─── CESD-R answers sync ─────────────────────────────────────────────
export async function syncCesdrAnswers(respondentCode: string, answers: Record<number, number>, totalScore: number, highRisk: boolean) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync CESD-R — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing CESD-R for:', respondentCode, 'score:', totalScore)
  const { error } = await supabase
    .from('cesdr_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
      total_score: totalScore,
      high_risk: highRisk,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing CESD-R:', error.message, error.details)
  else console.log('[Supabase] CESD-R synced OK')
}

// ─── PSQI answers sync ───────────────────────────────────────────────
export async function syncPsqiAnswers(respondentCode: string, answers: Record<string, unknown>, totalScore: number) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync PSQI — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing PSQI for:', respondentCode, 'score:', totalScore)
  const { error } = await supabase
    .from('psqi_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
      total_score: totalScore,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing PSQI:', error.message, error.details)
  else console.log('[Supabase] PSQI synced OK')
}

// ─── Screen Time answers sync ────────────────────────────────────────
export async function syncScreentimeAnswers(respondentCode: string, answers: Record<string, unknown>) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync ScreenTime — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing ScreenTime for:', respondentCode)
  const { error } = await supabase
    .from('screentime_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing ScreenTime:', error.message, error.details)
  else console.log('[Supabase] ScreenTime synced OK')
}

// ─── MOS answers sync ────────────────────────────────────────────────
export async function syncMosAnswers(respondentCode: string, answers: Record<number, number>, totalScore: number) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync MOS — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing MOS for:', respondentCode, 'score:', totalScore)
  const { error } = await supabase
    .from('mos_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
      total_score: totalScore,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing MOS:', error.message, error.details)
  else console.log('[Supabase] MOS synced OK')
}

// ─── Bullying answers sync ───────────────────────────────────────────
export async function syncBullyingAnswers(respondentCode: string, answers: Record<number, number>, victimScore: number) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync Bullying — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing Bullying for:', respondentCode, 'score:', victimScore)
  const { error } = await supabase
    .from('bullying_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
      victim_score: victimScore,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing Bullying:', error.message, error.details)
  else console.log('[Supabase] Bullying synced OK')
}

// ─── Religiosity answers sync ────────────────────────────────────────
export async function syncReligiosityAnswers(respondentCode: string, answers: Record<number, number>, totalScore: number) {
  if (!supabase) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  if (!respondentId) { console.error('[Supabase] Cannot sync Religiosity — respondent not found:', respondentCode); return }
  console.log('[Supabase] Syncing Religiosity for:', respondentCode, 'score:', totalScore)
  const { error } = await supabase
    .from('religiosity_answers')
    .upsert({
      respondent_id: respondentId,
      answers: answers,
      total_score: totalScore,
    }, { onConflict: 'respondent_id' })
  if (error) console.error('[Supabase] Error syncing Religiosity:', error.message, error.details)
  else console.log('[Supabase] Religiosity synced OK')
}

// ─── Audit log sync ──────────────────────────────────────────────────
export async function syncAuditLog(respondentCode: string | null, action: string, detail?: string) {
  if (!supabase || !respondentCode) return
  const respondentId = await getSupabaseRespondentId(respondentCode)
  // audit_logs.respondent_id is nullable, so we can insert even without UUID
  const { error } = await supabase
    .from('audit_logs')
    .insert({
      respondent_id: respondentId,
      action,
      detail: detail ?? null,
    })
  if (error) console.error('[Supabase] Error syncing audit log:', error.message)
}

// ─── Research code sync ──────────────────────────────────────────────
export async function syncResearchCode(code: string, school?: string | null, classGrade?: string | null) {
  if (!supabase) return
  const { error } = await supabase
    .from('research_codes')
    .upsert({
      code,
      school: school ?? null,
      class_grade: classGrade ?? null,
    }, { onConflict: 'code' })
  if (error) console.error('[Supabase] Error syncing research code:', error.message)
}

// ─── Update research code used status ────────────────────────────────
export async function syncResearchCodeUsed(code: string, used: boolean) {
  if (!supabase) return
  const { error } = await supabase
    .from('research_codes')
    .update({ used })
    .eq('code', code)
  if (error) console.error('[Supabase] Error updating code used:', error.message)
}
